apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: pipem.io
    component: api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      serviceAccountName: pipem-api-sa
      containers:
        - name: api
          image: {{ .Values.image }}:{{ .Values.version }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: pipem-config
          env:
            - name: PORT
              value: '8080'
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: pipem-secret
                  key: COOKIE_SECRET
            - name: 'MONGODB_URI'
              valueFrom:
                secretKeyRef:
                  name: pipem-secret
                  key: MONGODB_URI
